sudo: required
services:
- docker
language: ruby
rvm:
- 2.1.5
install:
- echo "Install task"
script:
- echo "Build start"
- "./ci-cd/helpers.rb"
- echo "Build done"
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
after_success:
- "./ci-cd/docker-build.rb"
env:
  global:
    - secure: "DKjS6bD3Vb+XR5ig0hjBGTifO0xnNmQr857fwNaIxNa8uYAVN3CET9ZBOKLPOVL+UrGDEe3tGAqahunRZFKLjFIifT3+1JuF/XdfEF9dGgJd6cKBGTwrAxrahT5kMbE2MJgrssCBL4Mg8t15OE7+/SsvPD8HHr4AdZZGNjYCKEM5H2g2DN1vugovXJD6ANKWAMEuUJnDNhMDUo3bIFiulePqxDdnUxvOrllifxwnKNTv6JvQ2FeI34D30qqrP6NkWZ7nGdmXPYuwBGs+4m16MprX9bNoFeHAKVMdW1JWyCtn6aoi2AdsOnHBlA9St7x6C9IU7ZtyFZp/NbW+FSWypPwHlWa7bL7BwHfjx85plOas76Jka5Hm6SsAjgGK3xyxqpcAFmz6rlwt3q7S0FRcNH5m5+TwGPl1ryYGB8UjTXU23cuO9rTx1rbuCK/TO1E4PmU+IHaRfeiiv8gxcwjTlWoahKlRkHmBcgIV5LF36sjSSlPmrvst3uz4N4vsUYkKR2IrHjLbuJjyPiuHsf5JMgHX7LCd3Cf91VJf7xQi6DJHdYDVqLYHn1WyaE4QHsvf+t7Hmh8Oy54/XhrC5SJMMtJy3I+ZW88hWs1utwIQW5gLl0xWEAfhhcDHIgnxYj6PuSA6yzmTOsxatCw/UpNUK80/R7nzH9QrEJFV0bVUa2c="
