version: '2'
services:
  postgresql:
    image: postgres:9.6.2-alpine
    container_name: postresql-dev
    environment:
      POSTGRES_PASSWORD: imi-maps
      POSTGRES_USER: imi-maps
      POSTGRES_DB: imi-maps
    ports:
      - 5432:5432

  imi-maps:
    build: ../../
    image: htw/imi-maps:development
    container_name: imi-maps-development
    depends_on:
      - postgresql
    env_file: .env-development
    volumes:
      - imi-maps-sync:/usr/src/app:rw
    links:
      - postgresql
    ports:
      - 80:80
volumes:
  imi-maps-sync:
    external: true
