version: '2'
services:
  postgresql:
    image: postgres:9.6.2-alpine
    container_name: postresql-staging
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5432:5432

  imimaps:
    image: imimaps/staging:${VERSION}
    container_name: imimaps-staging
    depends_on:
      - postgresql
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    links:
      - postgresql
    ports:
      - 4000:80
