version: '2'
services:
  postgresql:
    image: postgres:9.6.2-alpine
    container_name: postresql-production
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5432:5432

  imimaps:
    image: imimaps/production:${TAG}
    container_name: imimaps-production
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    depends_on:
      - postgresql
    links:
      - postgresql
    ports:
      - 4000:80
